import type { Metadata } from "next"
import { Geist } from "next/font/google"
import "./globals.css"
import { Providers } from "@/lib/Providers"
import { TooltipProvider } from "@/components/ui/Tooltip"
import { AuthProvider } from "@/context/AuthContext"
import { Toaster } from "@/components/ui/Toaster"
import { Toaster as Sonner } from "@/components/ui/Sonner"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Networking",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="w-screen h-screen">
      <body className={`${geistSans.variable} antialiased h-full`}>
        <TooltipProvider>
          <AuthProvider>
            <Toaster />
            <Sonner />
            <Providers>{children}</Providers>
          </AuthProvider>
        </TooltipProvider>
      </body>
    </html>
  )
}
